Add default realm to example krb5.conf
kurokobo/awx-on-k3s pull request #290
Opened 2024-01-05 21:07 UTC by CaptainStealthy

This example caused the test playbook to fail with an error saying that the Kerberos config did not specify a default realm.

Once I added that extra line to the configmap, it worked great. Just thought I would contribute that back as a PR for anyone else that finds this in the future.

Thanks!

2024-01-07 05:10 UTC, kurokobo requested changes
@CaptainStealthy 
Hi, thanks for your contribution!
I did not include `default_realm` in the documentation because it worked without it in the lab I tested.
However, this is certainly a reasonable change, as it is more likely to work in more cases if the `default_realm` is present.

One thing, can you add same configuration to following two example outputs? (Searchng `libdefaults` in the page could helps you to determine where the configuration file is dumped in the guide)

- Under **Create ConfigMap for `krb5.conf`**
  - The output for `$ kubectl -n awx get configmap awx-kerberos-config -o yaml`
- Under **Ensure your `krb5.conf` is mounted**
  - The output for `bash-5.1$ cat /etc/krb5.conf`

2024-01-09 15:15 UTC, kurokobo approved these changes

2024-01-09 15:15 UTC, merged

2024-01-09 16:17 UTC, kurokobo commented
> One thing, can you add same configuration to following two example outputs?

I've made these changes on my side and merged this PR. Thanks for your contribution!

2024-01-09 19:31 UTC, CaptainStealthy commented
Thanks for doing that!

I apologize, I have been completely swamped the past few days, so I didn't get a chance to make that change.