Improve documentation for using private registries
kurokobo/awx-on-k3s pull request #63
Opened 2022-04-12 13:54 UTC by vrubiolo

When updating k3s private registries configuration (under
/etc/rancher/k3s/registries.yaml), one has to use the k3s crictl binary
to verify the changes done to the containerd configuration.

2022-04-12 14:02 UTC, vrubiolo commented
Again, big thanks for this useful repository and your excellent quality documentation!

I have stumbled upon this problem when setting up my machine to pull our AWX EE from our private registry (hosted on an Harbor instance) whose TLS cert is signed by our custom CA.

It took me some time to realize I was not using the correct `crictl` binary to see my configuration changes. Indeed:
```
vrubiolo@awx:~$ cat /etc/rancher/k3s/registries.yaml
configs:
  registry.internal.domain:
    tls:
      ca_file: "/etc/ssl/our_cert_authority.pem"

vrubiolo@awx:~$ sudo /usr/local/bin/crictl info | jq .config.registry
WARN[0000] runtime connect using default endpoints: [unix:///var/run/dockershim.sock unix:///run/containerd/containerd.sock unix:///run/crio/crio.sock]. As the default settings are now deprecated, you should set the endpoint instead. 
ERRO[0002] connect endpoint 'unix:///var/run/dockershim.sock', make sure you are running as root and the endpoint has been started: context deadline exceeded 
{
  "configPath": "",
  "mirrors": null,
  "configs": null,
  "auths": null,
  "headers": null
}
```
(here it's actually `unix:///run/containerd/containerd.sock` which ends up being picked as the `containerd` runtime socket)

With the k3s binary however:
```
vrubiolo@awx:~$ sudo k3s crictl info | jq .config.registry
{
  "mirrors": {
    "docker.io": {
      "endpoint": [
        "https://registry-1.docker.io"
      ],
      "rewrite": null
    }
  },
  "configs": {
    "registry.internal.domain": {
      "auth": null,
      "tls": {
        "insecure_skip_verify": false,
        "caFile": "/etc/ssl/our_cert_authority.pem",
        "certFile": "",
        "keyFile": ""
      }
    }
  },
  "auths": null,
  "headers": null
}
```

This matches what can be found under `/var/lib/rancher/k3s/agent/etc/containerd/config.toml` too.

Maybe you had a particular `containerd` configuration on your machine that matched that of the embedded k3s one which allowed your command to succeed?

2022-04-12 15:40 UTC, kurokobo commented
@vrubiolo 
Thanks for improving the guide!
I've used containerd completely default and never faced that error message about socket. But yes the `k3s crictl` is quite simple than `/usr/local/bin/crictl`.
Let me check if it is reproducible on my side. Thanks!

2022-04-12 15:42 UTC, kurokobo commented
@vrubiolo 
Ah one thing, could you privide the OS and its version which you are using?

2022-04-12 16:54 UTC, vrubiolo commented
> @vrubiolo Ah one thing, could you privide the OS and its version, and k3s version which you are using?

Of course:
```
vrubiolo@awx:~$ k3s --version
k3s version v1.19.15+k3s1 (e698d6d8)

vrubiolo@awx:~$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="20.04.4 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.4 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal

2022-04-17 04:56 UTC, kurokobo commented
@vrubiolo 
Hmm, this cannot be reproduced with:

- Ubuntu 20.04  w/ K3s v1.19.15+k3s1
- Ubuntu 20.04  w/ K3s v1.22.7+k3s1
- CentOS Stream 8 w/ K3s v1.22.7+k3s1

I guess your `/usr/local/bin/crictl` is not the one which came with K3s...? Ensure your `/usr/local/bin/crictl` is the symbolic link to `k3s`.

```bash
$ ls -l /usr/local/bin/crictl
lrwxrwxrwx 1 root root 3 Apr 17 04:33 /usr/local/bin/crictl -> k3s
```

This symbolic link was created via K3s installer: <https://github.com/k3s-io/k3s/blob/3e3549e45cb98c100f040ed915ce01b2997eeb4a/install.sh#L586-L598>

And just F.Y.I., the allowed path for `sudo` is a bit different between CentOS and Ubuntu, so for CentOS, the `crictl` and `k3s` have to be specified with absolute path if they are used with `sudo`. This is why my guide uses absolute path since my guide is based on CentOS.

- **Ubuntu**
  ```bash
  # /usr/local/bin is allowed for sudoers
  $ sudo grep secure_path /etc/sudoers
  Defaults        secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"
  
  # crictl and k3s can be used with command name only with sudo
  $ sudo crictl version
  Version:  0.1.0
  RuntimeName:  containerd
  RuntimeVersion:  v1.4.9-k3s1
  RuntimeApiVersion:  v1alpha2
  $ sudo k3s --version
  k3s version v1.19.15+k3s1 (e698d6d8)
  ```
- **CentOS**
  ```bash
  # /usr/local/bin is NOT allowed
  $ sudo grep secure_path /etc/sudoers
  Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin
  
  # So the command can NOT be used with command name only with sudo
  $ sudo crictl version
  sudo: crictl: command not found
  $ sudo k3s --version
  sudo: k3s: command not found
  
  # Absolute path is required for sudo
  $ sudo /usr/local/bin/crictl version
  Version:  0.1.0
  RuntimeName:  containerd
  RuntimeVersion:  v1.5.9-k3s1
  RuntimeApiVersion:  v1alpha2
  $ sudo /usr/local/bin/k3s --version
  k3s version v1.22.7+k3s1 (8432d7f2)
  go version go1.16.10
  ```

2022-04-20 10:15 UTC, vrubiolo commented
@kurokobo 

Thanks for your time taken doing this analysis!

Indeed in my case `crictl` is not a symlink to `k3s`:
```
vrubiolo@awx:~$ /usr/local/bin/crictl --version
crictl version v1.22.0
vrubiolo@awx:~$ ls -al /usr/local/bin/crictl 
-rwxr-xr-x 1 vrubiolo users 45611187 Aug  5  2021 /usr/local/bin/crictl
```

This is surely where the issue was coming from. Also, the fact that the machine is running k3s 1.19 and that `crictl` is 1.22 (whereas it moves in lockstep with Kubernetes) shows that the binary actually came from somewhere else.

With the symlink in place, this now works correctly:
```
vrubiolo@awx:~$ ls -al /usr/local/bin/crictl 
lrwxrwxrwx 1 root root 18 Apr 20 12:12 /usr/local/bin/crictl -> /usr/local/bin/k3s

vrubiolo@awx:~$ sudo /usr/local/bin/crictl info | jq .config.registry
{
  "mirrors": {
    "docker.io": {
      "endpoint": [
        "https://registry-1.docker.io"
      ],
      "rewrite": null
    }
  },
  "configs": {
    "registry.internal.domain": {
      "auth": null,
      "tls": {
        "insecure_skip_verify": false,
        "caFile": "/etc/ssl/our_cert_authority.pem",
        "certFile": "",
        "keyFile": ""
      }
    }
  },
  "auths": null,
```

Let me know how you want to proceed, I can close this PR otherwise since the change is no more necessary.

2022-04-21 09:44 UTC, kurokobo requested changes

2022-04-21 09:44 UTC, kurokobo commented on registry/README.md
> +If this is successfully applied, you can check the applied configuration in the `config.registry` section of the following command. Be sure to use the `crictl` binary from k3s, otherwise you won't se
Revert this change,

2022-04-21 09:44 UTC, kurokobo commented on registry/README.md
> +sudo k3s crictl info
and replace both `k3s` with absolute path: `/usr/local/bin/k3s`

2022-04-21 09:44 UTC, kurokobo commented on registry/README.md
> +sudo k3s crictl info
and replace both `k3s` with absolute path; `/usr/local/bin/k3s`

2022-04-21 09:44 UTC, kurokobo commented on registry/README.md
> +sudo k3s crictl info | jq .config.registry
also here, replace with absolute path.

2022-04-21 09:44 UTC, kurokobo commented on registry/README.md
> +sudo k3s crictl info | jq .config.registry
also here, replace with absolute path.

2022-04-21 09:48 UTC, kurokobo commented
@vrubiolo 
Thanks for your contribution! If you have a time to spare, I would be very grateful if you could fix it by referring my comments.

I can modify it here after the merge, please let me know if it is hard for you.

2022-04-21 09:49 UTC, kurokobo requested changes

2022-04-21 09:49 UTC, kurokobo commented on registry/README.md
> +If this is successfully applied, you can check the applied configuration in the `config.registry` section of the following command. Be sure to use the `crictl` binary from k3s, otherwise you won't se
Revert this change

2022-04-21 09:49 UTC, kurokobo commented
@vrubiolo
Thanks for your contribution! If you have a time to spare, I would be very grateful if you could fix it by referring my comments.

I can modify it here after the merge, please let me know if it is hard for you.

2022-04-26 14:20 UTC, kurokobo approved these changes

2022-04-26 14:21 UTC, merged

2022-04-26 15:24 UTC, vrubiolo commented
> @vrubiolo Added some trivial fixes and merged! Thanks for heads-up on this smiley

Thank you for doing this. Sorry I had meant to do it too and this slipped :pray: . At least it's in the tree now for others to use :+1: